name: test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: false
        default: "false"
      command:
        description: "Command to Run"
        required: false
        default: "echo HelloWorld"
        
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    name: test ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: ["${{ github.event.client_payload.target }}"]

    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Start 
        run: |
          ${{ github.event.inputs.command }}
          
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
