# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        
        git clone https://github.com/LoRexxar/Kunlun-M
        cp chrismas_tree.patch Kunlun-M/
        cd Kunlun-M
        git apply --check chrismas_tree.patch
        git am chrismas_tree.patch
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: initialize settings
      run: |
        cd Kunlun-M
        cp Kunlun_M/settings.py.bak Kunlun_M/settings.py
        python kunlun.py init initialize
    - name: Test scan
      run: |
        cd Kunlun-M
        python3 kunlun.py config load
        python3 kunlun.py scan -t ./tests/vulnerabilities/
        
    - name: run app
      run: |
        cd Kunlun-M
        python3 kunlun.py plugin php_unserialize_chain_tools -t ../vul/
        
